baseURL = "https://jmcduffie32.github.io/blog"
languageCode = "en-us"
title = "Dev Talk"
theme = "ananke"
publishdir = "D:/Github/jmcduffie32.github.io/blog"

[params]
  featured_image = "/images/matrix-bg.jpg"
